/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./../components/common/BackTop.vue')['default']
    BaseButton: typeof import('./../components/common/BaseButton.vue')['default']
    BaseCard: typeof import('./../components/common/BaseCard.vue')['default']
    Empty: typeof import('./../components/common/Empty.vue')['default']
    Footer: typeof import('./../components/layout/Footer.vue')['default']
    LangSwitch: typeof import('./../components/common/LangSwitch.vue')['default']
    Loading: typeof import('./../components/common/Loading.vue')['default']
    MusicPlayer: typeof import('./../components/business/MusicPlayer.vue')['default']
    NavBar: typeof import('./../components/layout/NavBar.vue')['default']
    Pagination: typeof import('./../components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./../components/common/Skeleton.vue')['default']
    ThemeSwitch: typeof import('./../components/common/ThemeSwitch.vue')['default']
    VideoPlayer: typeof import('./../components/business/VideoPlayer.vue')['default']
  }
}
